### ISSUE TITLE
Loading a Mesh

### ISSUE THREAD

**Issue by ADefWebserver** [canhorn/EventHorizon.Blazor.TypeScript.Interop.Generator#1]
As discussed in the chat of this video;
https://www.twitch.tv/videos/682960182 (at 00:42:06)
It should be possible to load a mesh. However, it appears the required SceneLoader isn't implemented yet?

![image](https://user-images.githubusercontent.com/1857799/87862662-6b472480-c907-11ea-87c3-00e4a2a60884.png)

**Comment by canhorn** [comment]
SceneLoader is now generating in the Sample. 
There is an example in the Blazor project too.

**Comment by ADefWebserver** [comment]
That works, I was able to load an advanced mesh using:

```
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BabylonJS;
using EventHorizon.Blazor.BabylonJS.Model;

namespace EventHorizon.Blazor.BabylonJS.Pages
{
    public partial class LoadMesh
    {
        protected override void OnAfterRender(bool firstRender)
        {
            if (firstRender)
            {
                CreateScene();
            }
        }

        public void CreateScene()
        {
            var canvas = Canvas.GetElementById(
                "game-window"
            );
            var engine = new Engine(
                canvas,
                true
            );
            var scene = new Scene(
                engine
            );
            var light0 = new PointLight(
                "Omni",
                new Vector3(
                    0, -1, -1
                ),
                scene
            );
            var light1 = new HemisphericLight(
                "HemisphericLight",
                new Vector3(
                    0, 1, 0
                ),
                scene
            );
            var dummy3 = SceneLoader.ImportMesh(
                null,
                "assets/",
                "dummy3.babylon.json",
                scene
            );

            var freeCamera = new FreeCamera(
                "FreeCamera",
                new Vector3(
                    0,
                    5,
                    -10
                ),
                scene
            )

            {
                rotation = new Vector3(
                    0,
                    10,
                    -50
                ),
            };

            scene.activeCamera = freeCamera;

            freeCamera.setTarget(new Vector3(
                    0,
                    0,
                    0
                ));

            freeCamera.attachControl(
                canvas,
                false
            );

            scene.activeCamera.position.addInPlace(new Vector3(0, 0, 5));

            engine.runRenderLoop(() => Task.Run(() => scene.render(true, false)));
        }
    }
}
```

![image](https://user-images.githubusercontent.com/1857799/87887830-589f1f00-c9dd-11ea-9afd-879668e87218.png)

Is **ArcRotateCamera** planned?

Thanks!

**Comment by canhorn** [comment]
That is great!
If you need more of the BabylonJS API generated you can update the `generationList` variable with the Class API name you need:
[Program.cs](https://github.com/canhorn/EventHorizon.Blazor.TypeScript.Interop.Generator/blob/b1a0c5a29d5138437bc476d943d1e1672b6dd18b/Sample/EventHorizon.BabylonJS.Interop.Generator.ConsoleApp/Program.cs#L36)

And running `dotnet run` from the **EventHorizon.BabylonJS.Interop.Generator.ConsoleApp** project root will update the **_generated/EventHorizon.Blazor.BabylonJS.WASM** project. (it might get directory/file locking exception if its locked, the console app does some cleanup)

I tried and add more details to the Sample readme, if you have any pointers to clarifying anything I would love to hear them.

Thank You!

**Comment by ADefWebserver** [comment]
Got it! Thank You!
